### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dogerizergaming** [CakeKing64/P5IM-android-10-fix#1]
The app won't install

I'm on a Huawei P30 lite

**Comment by CakeKing64** [comment]
[Comment below this one is probably the correct answer](https://github.com/CakeKing64/P5IM-android-10-fix/issues/1#issuecomment-808935948)

but in case it isn't:

Make sure that installing from external sources is enabled

If not you can find it in (I'm pretty sure)
Settings > Security > Unknown Sources

If it still doesn't work try installing the original version found
[https://github.com/ngreenan/p5imapp/releases](https://github.com/ngreenan/p5imapp/releases)
and tell me if that works

and if that doesn't work you'll have to use ADB for me to be able to get the info I'll need, but I'll give you over to some nerd I know because my internet isn't really that usable due to maintenance that'll last a few days :(

**Comment by JuliannaG8** [comment]
In case you haven't got it fixed, try uninstalling the app, then reinstall it using one of CakeKing64's releases.

**Comment by dogerizergaming** [comment]
Kinda late but it worked, all i had to do was uninstall the original version and replace it with this one

**Comment by CakeKing64** [comment]
All good then, I now kinda feel stupid for not leading with that advice (seeing as I had to do the same thing myself at one point). Tech support I am not
